package com.example

import android.content.Context
import androidx.compose.runtime.*

object L {
    var currentLanguage by mutableStateOf("bn") // "bn" or "en"

    private var hasInitialized = false
    private lateinit var sharedPrefs: android.content.SharedPreferences

    fun init(context: Context) {
        if (hasInitialized) return
        sharedPrefs = context.applicationContext.getSharedPreferences("shikkhaloy_prefs", Context.MODE_PRIVATE)
        currentLanguage = sharedPrefs.getString("selected_language_code", "bn") ?: "bn"
        hasInitialized = true
    }

    fun setLanguage(context: Context, lang: String) {
        init(context)
        currentLanguage = lang
        sharedPrefs.edit().putString("selected_language_code", lang).apply()
    }

    // High performance translation lookup
    fun translate(bn: String): String {
        if (currentLanguage == "bn") return bn
        return translations[bn.trim()] ?: bn
    }

    // Translate notice titles, content, or local notification strings
    fun translateNotice(text: String): String {
        if (currentLanguage == "bn") return text
        var translated = text
        // Replace known sub-phrases/words for dynamic fields
        for ((bn, en) in translations) {
            if (bn.length > 3) {
                translated = translated.replace(bn, en)
            }
        }
        return translated
    }

    // Bengali to English translation map
    val translations = mapOf(
        "স্বাগতম শিক্ষালয়ে" to "Welcome to Shikkhaloy",
        "আপনার শিক্ষাগত যাত্রা সহজ করতে লগইন করুন" to "Log in to simplify your educational journey",
        "শিক্ষক বা শিক্ষার্থী হিসেবে যুক্ত হতে সাইন-আপ করুন" to "Sign up to join as a teacher or student",
        "নতুন অ্যাকাউন্ট তৈরি করুন" to "Sign Up",
        "ইমেইল" to "Email",
        "পাসওয়ার্ড" to "Password",
        "মেইল অ্যাড্রেস লিখুন" to "Enter email address",
        "পাসওয়ার্ড লিখুন" to "Enter password",
        "লগইন করুন" to "Login",
        "রেজিস্টার করুন" to "Register",
        "গুগল দিয়ে সাইন-ইন করুন" to "Sign in with Google",
        "ডিজিটাল স্কুল ম্যানেজমেন্ট প্ল্যাটফর্ম" to "Digital School Management Platform",
        "দ্রুত ডেমো মুডে প্রবেশ করুন" to "Enter Quick Demo Mode",
        "পছন্দসমূহ" to "Preferences",
        "থিম পরিবর্তন" to "Change Theme",
        "থিম নির্বাচন করুন" to "Select Theme",
        "লাইট থিম" to "Light Theme",
        "ডার্ক থিম" to "Dark Theme",
        "সিস্টেম ডিফল্ট" to "System Default",
        "লাইট, ডার্ক, সিস্টেম" to "Light, Dark, System",
        "ডাউনলোড করা ক্লাস ভিডিও ও পিডিএফ" to "Downloaded class videos and PDFs",
        "প্রশাসনিক প্যানেল" to "Administrative Panel",
        "অ্যাডমিন ড্যাশবোর্ড" to "Admin Dashboard",
        "ইউজার কন্ট্রোল, নোটিশ ও ডাটাবেজ নিয়ন্ত্রণ করুন" to "Control users, notices, and database",
        "এপ আপডেট" to "App Updates",
        "আপডেট চেক করা হচ্ছে..." to "Checking for updates...",
        "এপ আপডেট চেক করুন" to "Check App Updates",
        "এপ্লিকেশন এর নতুন আপডেট চেক করুন" to "Check for new application updates",
        "আপডেট পাবলিশ করুন" to "Publish Update",
        "ব্যবহারকারীদের জন্য নতুন আপডেট রিলিজ করুন" to "Release new update for users",
        "অ্যাকাউন্ট ও নিরাপত্তা" to "Account & Security",
        "সাইন-আপ করুন" to "Sign Up",
        "অ্যাকাউন্ট নেই? সাইন-আপ করুন" to "Don't have an account? Sign Up",
        "ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন" to "Already have an account? Login",
        "গুগল দিয়ে লগইন করুন" to "Sign in with Google",
        "অনুগ্রহ করে সঠিক ইমেইল ও পাসওয়ার্ড দিন" to "Please enter a valid email and password",
        "লগইন সফল হয়েছে" to "Login successful",
        "লগইন ব্যর্থ হয়েছে" to "Login failed",
        "লগ আউট" to "Logout",
        "লগ আউট করুন" to "Logout",
        "আপনি কি নিশ্চিত যে আপনি লগ আউট করতে চান?" to "Are you sure you want to logout?",
        "হ্যাঁ, লগ আউট করুন" to "Yes, Logout",
        "না" to "No",
        "বাতিল" to "Cancel",
        "কোর্সসমূহ" to "Courses",
        "আমার কোর্স" to "My Courses",
        "ড্যাশবোর্ড" to "Dashboard",
        "কোর্স" to "Courses",
        "ম্যানেজমেন্ট" to "Management",
        "শিক্ষক ড্যাশবোর্ড" to "Teacher Dashboard",
        "আপনার ক্লাসরুম ও কোর্সের কাজগুলো পরিচালনা করুন" to "Manage your classroom and course tasks",
        "প্রোফাইল" to "Profile",
        "সেটিংস" to "Settings",
        "শিক্ষালয়" to "Shikkhaloy",
        "সকল কোর্স" to "All Courses",
        "আমার কোর্সসমূহ" to "My Courses",
        "আপনার তৈরি করা সকল কোর্স এখানে দেখুন" to "View all courses created by you",
        "কোর্সটি ডিলিট করুন" to "Delete Course",
        "আপনি কি নিশ্চিত যে আপনি এই কোর্সটি ডিলিট করতে চান? এই কাজ মুছে ফেলা যাবে না।" to "Are you sure you want to delete this course? This action cannot be undone.",
        "নিশ্চিত করতে কোর্সের নাম লিখুন: " to "Type course name to confirm: ",
        "কোর্সের নাম" to "Course Name",
        "ডিলিট করুন" to "Delete",
        "যোগ দিন" to "Join",
        "ক্লাস যোগ" to "Add Class",
        "ক্লাস লিংক যোগ" to "Add Class Links",
        "চ্যানেল" to "Channels",
        "হোম ওয়ার্ক" to "Homework",
        "শিক্ষার্থীদের পরিচালনা" to "Manage Students",
        "মেন্টর তালিকা" to "Mentor List",
        "শিক্ষা প্রতিষ্ঠান" to "Educational Institution",
        "যোগাযোগ নম্বর" to "Contact Number",
        "আপনার প্রোফাইল" to "Your Profile",
        "প্রোফাইল এডিট" to "Edit Profile",
        "ভাষা" to "Language",
        "ভাষা পরিবর্তন" to "Change Language",
        "এই ডিভাইস থেকে লগ আউট করুন" to "Log out from this device",
        "সংরক্ষণ করুন" to "Save",
        "সেভ করুন" to "Save",
        "অনুগ্রহ করে সব তথ্য দিন" to "Please provide all information",
        "প্রোফাইল সফলভাবে আপডেট হয়েছে" to "Profile updated successfully",
        "শিক্ষার্থী তালিকা" to "Student List",
        "অফলাইন ডাউনলোড" to "Offline Downloads",
        "ডাউনলোডকৃত ফাইলসমূহ" to "Downloaded Files",
        "কোনো ডাউনলোড করা ফাইল নেই" to "No downloaded files",
        "ফাইল সাইজ" to "File Size",
        "ডাউনলোড করা হয়েছে" to "Downloaded",
        "ডাউনলোড ব্যর্থ" to "Download Failed",
        "ডাউনলোড হচ্ছে" to "Downloading",
        "নতুন আপডেট পাওয়া গেছে" to "New Update Available",
        "আপডেট করুন" to "Update Now",
        "পরে করুন" to "Later",
        "জরুরি নোটিশ" to "Emergency Notice",
        "ঠিক আছে, বুঝতে পেরেছি" to "OK, I understand",
        "পাবলিশ করুন" to "Publish",
        "বন্ধ করুন" to "Close",
        "বিস্তারিত" to "Details",
        "সম্পূর্ণ বিবরণ" to "Full Description",
        "ক্লাসসমূহ" to "Classes",
        "লেকচার ক্লাস" to "Lecture Class",
        "সলভিং ক্লাস" to "Solving Class",
        "গাইডলাইন ক্লাস" to "Guideline Class",
        "অতিরিক্ত ক্লাস" to "Extra Class",
        "লেকচার শিট/PDF" to "Lecture Sheet/PDF",
        "লাইভ ক্লাস লিংক" to "Live Class Link",
        "রেকর্ড ভিডিও লিংক" to "Recorded Video Link",
        "হোমওয়ার্ক লিংক" to "Homework Link",
        "ক্লাস স্লাইড (PDF) লিংক" to "Class Slide (PDF) Link",
        "তারিখ" to "Date",
        "সময়" to "Time",
        "মেন্টর" to "Mentor",
        "শ্রেণী" to "Class",
        "পরীক্ষা" to "Exam",
        "কুইজ" to "Quiz",
        "ফলাফল" to "Result",
        "ভর্তি তথ্য" to "Admission Info",
        "যোগাযোগ" to "Contact",
        "হেল্পলাইন" to "Helpline",
        "বিজ্ঞপ্তি" to "Notices",
        "সব নোটিশ" to "All Notices",
        "কোনো নোটিশ নেই" to "No notices",
        "কোনো ক্লাস নেই" to "No classes",
        "কোনো কোর্স নেই" to "No courses",
        "শিক্ষক" to "Teacher",
        "শিক্ষার্থী" to "Student",
        "অ্যাডমিন" to "Admin",
        "রোল" to "Role",
        "নাম" to "Name",
        "মোবাইল নম্বর" to "Mobile Number",
        "নিবন্ধন করুন" to "Register",
        "পাবলিশড" to "Published",
        "টাকা" to "BDT",
        "ফি" to "Fee",
        "ফ্রি" to "Free",
        "কোর্স কিনুন" to "Buy Course",
        "ভর্তি হন" to "Enroll Now",
        "আপনার পেমেন্ট ভেরিফাই করা হচ্ছে" to "Verifying your payment",
        "পেমেন্ট সফল" to "Payment Successful",
        "পেমেন্ট ব্যর্থ" to "Payment Failed",
        "অনুমোদন পেন্ডিং" to "Approval Pending",
        "অনুমোদিত" to "Approved",
        "বাতিল করা হয়েছে" to "Rejected",
        "আজকের ক্লাস" to "Today's Class",
        "আগামীকালের ক্লাস" to "Tomorrow's Class",
        "পূর্ববর্তী ক্লাস" to "Previous Class",
        "কোনো ক্লাস পাওয়া যায়নি" to "No classes found",
        "ক্লাস লিংক যোগ করুন" to "Add Class Links",
        "তারিখ নির্বাচন করুন" to "Select Date",
        "এই তারিখে কোনো ক্লাস পাওয়া যায়নি" to "No classes found for this date",
        "ক্লাস লিংক সফলভাবে আপডেট করা হয়েছে" to "Class links updated successfully",
        "নির্বাচন করুন" to "Select",
        "বাছাই করুন" to "Choose",
        "ভিডিও প্লেয়ার" to "Video Player",
        "অফলাইন মোড" to "Offline Mode",
        "ইন্টারনেট কানেকশন নেই" to "No Internet Connection",
        "আবার চেষ্টা করুন" to "Try Again",
        "তথ্য লোড হচ্ছে" to "Loading info",
        "দয়া করে অপেক্ষা করুন" to "Please wait",
        "সব" to "All",
        "লেকচার" to "Lectures",
        "পরীক্ষা সমূহ" to "Exams",
        "রুটিন" to "Routine",
        "সিলেবাস" to "Syllabus",
        "নোট" to "Notes",
        "গ্রুপ চ্যাট" to "Group Chat",
        "লাইভ চ্যাট" to "Live Chat",
        "চ্যানেল সমুহ" to "Channels",
        "আমার চ্যানেল" to "My Channel",
        "সাবস্ক্রাইব" to "Subscribe",
        "সাবস্ক্রাইবড" to "Subscribed",
        "পোস্ট করুন" to "Post",
        "মন্তব্য" to "Comment",
        "লাইক" to "Like",
        "শেয়ার" to "Share",
        "রিপোর্ট" to "Report",
        "ব্লক" to "Block",
        "আনব্লক" to "Unblock",
        "ইউজার নিষিদ্ধ" to "User Banned",
        "আপনি এই কোর্স থেকে নিষিদ্ধ হয়েছেন" to "You have been banned from this course",
        "কোনো মেন্টর নেই" to "No mentors",
        "মেন্টর যোগ করুন" to "Add Mentor",
        "শিক্ষার্থী যোগ করুন" to "Add Student",
        "শিক্ষার্থী পরিচালনা করুন" to "Manage Students",
        "পেমেন্ট হিস্ট্রি" to "Payment History",
        "পেমেন্ট করুন" to "Make Payment",
        "লেনদেন আইডি" to "Transaction ID",
        "টাকার পরিমাণ" to "Amount",
        "পেমেন্ট মেথড" to "Payment Method",
        "বিকাশ" to "Bkash",
        "রকেট" to "Rocket",
        "নগদ" to "Nagad",
        "উপায়" to "Upay",
        "কার্ড" to "Card",
        "নিশ্চিত করুন" to "Confirm",
        "সচল ডিভাইস সমূহ" to "Active Devices",
        "ডিভাইস নাম" to "Device Name",
        "লগইনের সময়" to "Login Time",
        "রিমুভ করুন" to "Remove",
        "সফল" to "Success",
        "ব্যর্থ" to "Failed",
        "পেন্ডিং" to "Pending",
        "অনুমোদন" to "Approve",
        "প্রত্যাখান" to "Reject",
        "মুছে ফেলুন" to "Delete",
        "সম্পাদনা" to "Edit",
        "এডিট করুন" to "Edit",
        "যোগ করুন" to "Add",
        "তৈরি করুন" to "Create",
        "নতুন কোর্স" to "New Course",
        "কোর্স টাইটেল" to "Course Title",
        "কোর্স বিবরণ" to "Course Description",
        "কোর্স ফি" to "Course Fee",
        "কোর্স ইমেজ" to "Course Image",
        "কোর্স লোগো" to "Course Logo",
        "কোর্স ব্যানার" to "Course Banner",
        "ক্লাস সংখ্যা" to "No. of Classes",
        "মোট ক্লাস" to "Total Classes",
        "ঘণ্টা" to "Hours",
        "মিনিট" to "Minutes",
        "সেকেন্ড" to "Seconds",
        "দিন" to "Days",
        "মাস" to "Months",
        "বছর" to "Years",
        "আজ" to "Today",
        "গতকাল" to "Yesterday",
        "আগামীকাল" to "Tomorrow",
        "গত" to "Last",
        "পরবর্তী" to "Next",
        "আগের" to "Previous"
    )
}

@Composable
fun String.t(): String {
    val lang = L.currentLanguage
    return L.translate(this)
}
